import { useEnvContext } from "next-runtime-env";


export function useConstants() {
    const { 
        NEXT_PUBLIC_DEPARTURE_DATE_MIN_DAYS, 
        NEXT_PUBLIC_DEPARTURE_DATE_MAX_DAYS, 
        NEXT_PUBLIC_DEPARTURE_DATE_DATE_FROM,
        NEXT_PUBLIC_DEPARTURE_DATE_DATE_TO,
    } = useEnvContext();

    const DEPARTURE_DATE_DAYS_MIN = parseInt(NEXT_PUBLIC_DEPARTURE_DATE_MIN_DAYS || '7');
    const DEPARTURE_DATE_DAYS_MAX = parseInt(NEXT_PUBLIC_DEPARTURE_DATE_MAX_DAYS || '60');
    const DEPARTURE_DATE_DATE_FROM = NEXT_PUBLIC_DEPARTURE_DATE_DATE_FROM || '';
    const DEPARTURE_DATE_DATE_TO = NEXT_PUBLIC_DEPARTURE_DATE_DATE_TO || '';

    return {
        DEPARTURE_DATE_DAYS_MIN,
        DEPARTURE_DATE_DAYS_MAX,
        DEPARTURE_DATE_DATE_FROM,
        DEPARTURE_DATE_DATE_TO,
    }
}
